name: seiji annotations
email: sato@seiji.co
description: Annotations
url: "http://annotations.seiji.co"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

plugins_dir: [jekyll-hyphenate_filter]

defaults:
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      source:       "https://annotations.seiji.co"
      tags:         ""

sass:
  sass_dir:         _sass
  style:            :compressed
